[levelplay]
title = Unity LevelPlay
group = Runtime
help = Settings for the Unity LevelPlay mediation extension

version.default = 2.0.2

admob_android.private = 1
admob_android.type = bool
admob_android.default = 0
admob_android.label = Google AdMob Android

android_google_identifiers.private = 1
android_google_identifiers.type = bool
android_google_identifiers.default = 1
android_google_identifiers.label = Include Google advertising identifiers on Android

applovin_android.private = 1
applovin_android.type = bool
applovin_android.default = 0
applovin_android.label = AppLovin Android

aps_android.private = 1
aps_android.type = bool
aps_android.default = 0
aps_android.label = Amazon Publisher Services Android

aps_android_app_id.private = 1
aps_android_app_id.type = string
aps_android_app_id.label = Amazon Publisher Services Android App ID

bidmachine_android.private = 1
bidmachine_android.type = bool
bidmachine_android.default = 0
bidmachine_android.label = BidMachine Android

bigo_android.private = 1
bigo_android.type = bool
bigo_android.default = 0
bigo_android.label = BIGO Ads Android

chartboost_android.private = 1
chartboost_android.type = bool
chartboost_android.default = 0
chartboost_android.label = Chartboost Android

dt_exchange_android.private = 1
dt_exchange_android.type = bool
dt_exchange_android.default = 0
dt_exchange_android.label = DT Exchange Android

hyprmx_android.private = 1
hyprmx_android.type = bool
hyprmx_android.default = 0
hyprmx_android.label = HyprMX Android

inmobi_android.private = 1
inmobi_android.type = bool
inmobi_android.default = 0
inmobi_android.label = InMobi Android

liftoff_android.private = 1
liftoff_android.type = bool
liftoff_android.default = 0
liftoff_android.label = Liftoff Monetize Android

line_android.private = 1
line_android.type = bool
line_android.default = 0
line_android.label = LY Ads Network Android

meta_android.private = 1
meta_android.type = bool
meta_android.default = 0
meta_android.label = Meta Audience Network Android

mintegral_android.private = 1
mintegral_android.type = bool
mintegral_android.default = 0
mintegral_android.label = Mintegral Android

mobilefuse_android.private = 1
mobilefuse_android.type = bool
mobilefuse_android.default = 0
mobilefuse_android.label = MobileFuse Android

moloco_android.private = 1
moloco_android.type = bool
moloco_android.default = 0
moloco_android.label = Moloco Android

ogury_android.private = 1
ogury_android.type = bool
ogury_android.default = 0
ogury_android.label = Ogury Android

pangle_android.private = 1
pangle_android.type = bool
pangle_android.default = 0
pangle_android.label = Pangle Android

pubmatic_android.private = 1
pubmatic_android.type = bool
pubmatic_android.default = 0
pubmatic_android.label = PubMatic Android

smaato_android.private = 1
smaato_android.type = bool
smaato_android.default = 0
smaato_android.label = Smaato Android

superawesome_android.private = 1
superawesome_android.type = bool
superawesome_android.default = 0
superawesome_android.label = SuperAwesome Android

unity_ads_android.private = 1
unity_ads_android.type = bool
unity_ads_android.default = 0
unity_ads_android.label = Unity Ads Android

verve_android.private = 1
verve_android.type = bool
verve_android.default = 0
verve_android.label = Verve Android

vk_android.private = 1
vk_android.type = bool
vk_android.default = 0
vk_android.label = VK Ad Network Android

yandex_android.private = 1
yandex_android.type = bool
yandex_android.default = 0
yandex_android.label = Yandex Ads Android

yso_android.private = 1
yso_android.type = bool
yso_android.default = 0
yso_android.label = YSO Network Android

ios_tracking_usage_description.private = 1
ios_tracking_usage_description.type = string
ios_tracking_usage_description.default = Your data will be used to provide a better and personalized ad experience.
ios_tracking_usage_description.label = iOS tracking usage description

admob_ios.private = 1
admob_ios.type = bool
admob_ios.default = 0
admob_ios.label = Google AdMob iOS

admob_ios_appid.private = 1
admob_ios_appid.type = string
admob_ios_appid.label = Google AdMob iOS App ID

applovin_ios.private = 1
applovin_ios.type = bool
applovin_ios.default = 0
applovin_ios.label = AppLovin iOS

aps_ios.private = 1
aps_ios.type = bool
aps_ios.default = 0
aps_ios.label = Amazon Publisher Services iOS

aps_ios_app_id.private = 1
aps_ios_app_id.type = string
aps_ios_app_id.label = Amazon Publisher Services iOS App ID

bidmachine_ios.private = 1
bidmachine_ios.type = bool
bidmachine_ios.default = 0
bidmachine_ios.label = BidMachine iOS

bigo_ios.private = 1
bigo_ios.type = bool
bigo_ios.default = 0
bigo_ios.label = BIGO Ads iOS

chartboost_ios.private = 1
chartboost_ios.type = bool
chartboost_ios.default = 0
chartboost_ios.label = Chartboost iOS

dt_exchange_ios.private = 1
dt_exchange_ios.type = bool
dt_exchange_ios.default = 0
dt_exchange_ios.label = DT Exchange iOS

hyprmx_ios.private = 1
hyprmx_ios.type = bool
hyprmx_ios.default = 0
hyprmx_ios.label = HyprMX iOS

inmobi_ios.private = 1
inmobi_ios.type = bool
inmobi_ios.default = 0
inmobi_ios.label = InMobi iOS

liftoff_ios.private = 1
liftoff_ios.type = bool
liftoff_ios.default = 0
liftoff_ios.label = Liftoff Monetize iOS

line_ios.private = 1
line_ios.type = bool
line_ios.default = 0
line_ios.label = LY Ads Network iOS

meta_ios.private = 1
meta_ios.type = bool
meta_ios.default = 0
meta_ios.label = Meta Audience Network iOS

mintegral_ios.private = 1
mintegral_ios.type = bool
mintegral_ios.default = 0
mintegral_ios.label = Mintegral iOS

mobilefuse_ios.private = 1
mobilefuse_ios.type = bool
mobilefuse_ios.default = 0
mobilefuse_ios.label = MobileFuse iOS

moloco_ios.private = 1
moloco_ios.type = bool
moloco_ios.default = 0
moloco_ios.label = Moloco iOS

ogury_ios.private = 1
ogury_ios.type = bool
ogury_ios.default = 0
ogury_ios.label = Ogury iOS

pangle_ios.private = 1
pangle_ios.type = bool
pangle_ios.default = 0
pangle_ios.label = Pangle iOS

pubmatic_ios.private = 1
pubmatic_ios.type = bool
pubmatic_ios.default = 0
pubmatic_ios.label = PubMatic iOS

smaato_ios.private = 1
smaato_ios.type = bool
smaato_ios.default = 0
smaato_ios.label = Smaato iOS

superawesome_ios.private = 1
superawesome_ios.type = bool
superawesome_ios.default = 0
superawesome_ios.label = SuperAwesome iOS

tencent_ios.private = 1
tencent_ios.type = bool
tencent_ios.default = 0
tencent_ios.label = Tencent Ads iOS

unity_ads_ios.private = 1
unity_ads_ios.type = bool
unity_ads_ios.default = 0
unity_ads_ios.label = Unity Ads iOS

verve_ios.private = 1
verve_ios.type = bool
verve_ios.default = 0
verve_ios.label = Verve iOS

vk_ios.private = 1
vk_ios.type = bool
vk_ios.default = 0
vk_ios.label = VK Ad Network iOS

yandex_ios.private = 1
yandex_ios.type = bool
yandex_ios.default = 0
yandex_ios.label = Yandex Ads iOS

yso_ios.private = 1
yso_ios.type = bool
yso_ios.default = 0
yso_ios.label = YSO Network iOS
